### ISSUE TITLE
Please add Logout method

### ISSUE THREAD

**Issue by rn70212** [worldwide-asset-exchange/waxjs#100]
There is no logout function . Please add it

**Comment by niksad8** [comment]
if you are saying that logout of the waxjs library that can work, if you mean logout of cloudwallet that wont be done cause that will log them out of all other websites. 
if i am getting this right we are meant to logout the user of the waxjs system so that you cant execute transactions on behalf of the user?

**Comment by niksad8** [comment]
this has now been added wax.logout() is the function you can log a user out of waxjs when you do wax.login() again it will start a new login flow. hope it helps
