### ISSUE TITLE
Broken programmatic login and logout

### ISSUE THREAD

**Issue by isebarn** [worldwide-asset-exchange/waxjs#174]
**1. Programmatically logging in the user: From documentation**

> The library can also be instantiated with the user account and the public keys. Due to the library contains the user information, the login step can be avoided.

```
const wax = new waxjs.WaxJS({
  rpcEndpoint: 'https://wax.greymass.com',
  userAccount: 'user1',
  pubKeys: ['EOS7rC8jFvFrPYDqp3Nh3HdRfL79h11B1JhPEXy85enF5wwYzF3Hk']
});
```

_**this doesnt work**_

**2. Logging out of an account: From documentation**

> You can now log a user out of the waxjs library, this is usefull if you want to logout one user and let them login with another account.
To do this just call `wax.logout()` that will be enough.

_**this doesnt work**_

**Comment by niksad8** [comment]
thanks looking it to it

**Comment by includenull** [comment]
@isebarn Can you expand on what doesn't work with these?

I have tested initiating with account and keys and this is working correctly for me.  
If the user is not logged in to Cloud Wallet with the correct account they will have to do so the next time they sign a transaction.

This method also can not be used to switch users between Cloud Wallet accounts since they can only be logged in to one at a time.

`wax.logout()` should also be used in conjunction with `tryAutoLogin: false` because if the user is logged in to Cloud Wallet and has auto login enabled then they will get automatically logged back if the page of your app reloads.

**Comment by isebarn** [comment]
@includenull what web framework are you using? I've tried with both VueJS and React
