### ISSUE TITLE
How to connect waxjs to testnet 

### ISSUE THREAD

**Issue by shamtroon** [worldwide-asset-exchange/waxjs#34]
Hello, I want to connect waxjs to test-net instead of using main-net, I tried it by replacing rpc-endpoint, but it didn't works 

`        this.wax = new waxjs.WaxJS('https://testnet.waxsweden.org/', null, null, false);`

**Comment by andrecrjr** [comment]
i really need to know about it too 😢

**Comment by porkchop** [comment]
Hey @shamtroon and @andrecrjr sorry for the late response. Right now testnet is unsupported. However we will be bringing that online very soon.

**Comment by tmyngu11** [comment]
How about connecting to the local docker environment? 
I see that its commented out on https://github.com/worldwide-asset-exchange/waxjs/blob/develop/dist-web/index.html#L24 
but when I try to login, a popup takes me to http://all-access.wax.test:8113/cloud-wallet/login/ and it cant be reached.

**Comment by shamtroon** [comment]
@tmyngu11 Yeah we can connect wax-cloud-wallet to local-net and testnet too, but can't perform the action like login, signing because you can't import private keys of you local network in wax-cloud-wallet.

**Comment by m6cheung** [comment]
Any news on this? I would really like to know as well.

**Comment by tmyngu11** [comment]
> Any news on this? I would really like to know as well.

just use the mainnet tbh

**Comment by includenull** [comment]
> How about connecting to the local docker environment?
> I see that its commented out on https://github.com/worldwide-asset-exchange/waxjs/blob/develop/dist-web/index.html#L24
> but when I try to login, a popup takes me to http://all-access.wax.test:8113/cloud-wallet/login/ and it cant be reached.

This is actually for use with our internal local test environments which are not public I'm afraid.

Adding support for WAX Cloud Wallet on testnet is one thing, but locally, without releasing all our other infrastructure is not possible since WAX Cloud Wallet is a hosted managed service.

We are looking into adding testnet support to WAX Cloud Wallet, but I have no solid eta for this.

For now I suggest using the Universal Authenticator Library with ual-wax package and ual-anchor so you can use your dapp with both WCW and Anchor, this will enable you to test login/logout with WCW and the rest of your testing with Anchor.

**Comment by includenull** [comment]
> Is ual-wax actually usable right now? I remember trying it out 2 months ago I think and I couldn't make it work.

ual-wax 1.5.1 is working fine, you may need to ensure it pulls the latest waxjs 1.0.4 however.
